import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import { Logo } from './components/Logo'

const sora = Sora({ subsets: ['latin'], variable: '--font-sora' })

export const metadata: Metadata = {
  title: 'My Contacts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <main className="flex min-h-screen flex-col items-center bg-primary-100 px-96 py-16 font-sora">
          <Logo />

          {children}
        </main>
      </body>
    </html>
  )
}
